name: mobile
description: "Brand & Creator influencer marketplace mobile app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  ionicons: ^0.2.2

  # Navigation
  go_router: ^14.8.1

  # State Management
  provider: ^6.1.2

  # Networking
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.5

  # Media
  image_picker: ^1.1.2
  file_picker: ^8.1.7

  # WebSocket / Real-time
  web_socket_channel: ^3.0.2
  pusher_channels_flutter: ^2.3.1

  # Notifications
  # firebase_messaging: ^15.1.6
  # flutter_local_notifications: ^18.0.1

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.3.1
  mime: ^2.0.0
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  flutter_local_notifications: ^22.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
